<?php
/**
 * Web installer — first-run setup wizard.
 *
 * Steps:
 *   1  Prerequisites check
 *   2  Database connection + write conf/db.php
 *   3  Schema initialisation (CREATE TABLE IF NOT EXISTS)
 *   4  Admin account creation
 *   done  Redirect to app
 *
 * Guard: if conf/db.php exists AND app_users has an admin → redirect to index.php.
 *
 * @license AGPL-3.0-or-later
 */

declare(strict_types=1);

define('INSTALL_MODE', true);

$confFile   = __DIR__ . '/../conf/db.php';
$schemaFile = __DIR__ . '/../schema.sql';
$step       = $_GET['step'] ?? '1';
$errors     = [];
$success    = null;

// ---------- Guard — already installed ----------
if (file_exists($confFile)) {
    require_once $confFile;
    try {
        $h = defined('DB_HOST') ? DB_HOST : 'localhost';
        $u = defined('DB_USER') ? DB_USER : '';
        $p = defined('DB_PASS') ? DB_PASS : '';
        $d = defined('DB_NAME') ? DB_NAME : '';
        $chk = new PDO("mysql:host=$h;dbname=$d;charset=utf8mb4", $u, $p, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        $adminCount = (int)$chk->query("SELECT COUNT(*) FROM app_users WHERE role='admin' AND is_active=1")->fetchColumn();
        if ($adminCount > 0) {
            header('Location: index.php');
            exit;
        }
        // DB configured but no admin yet — skip to step 4
        if ($step === '1' || $step === '2' || $step === '3') {
            header('Location: install.php?step=4');
            exit;
        }
    } catch (Exception) {
        // conf exists but connection fails — continue installer
    }
}

// ---------- Step handlers ----------

// Step 2 POST — test connection + write conf/db.php
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === '2') {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbPort = (int)($_POST['db_port'] ?? 3306);
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = $_POST['db_pass'] ?? '';

    if (!$dbName) $errors[] = 'Nom de la base de données requis.';
    if (!$dbUser) $errors[] = 'Utilisateur requis.';

    if (!$errors) {
        try {
            $dsn = "mysql:host={$dbHost};port={$dbPort};dbname={$dbName};charset=utf8mb4";
            new PDO($dsn, $dbUser, $dbPass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

            // Write conf/db.php
            $confDir = dirname($confFile);
            if (!is_dir($confDir)) {
                mkdir($confDir, 0750, true);
            }
            $confContent = sprintf(
                "<?php\n// Generated by installer — %s\ndefine('DB_HOST', %s);\ndefine('DB_PORT', %d);\ndefine('DB_NAME', %s);\ndefine('DB_USER', %s);\ndefine('DB_PASS', %s);\n",
                date('Y-m-d H:i:s'),
                var_export($dbHost, true),
                $dbPort,
                var_export($dbName, true),
                var_export($dbUser, true),
                var_export($dbPass, true)
            );
            if (file_put_contents($confFile, $confContent) === false) {
                $errors[] = "Impossible d'écrire <code>{$confFile}</code>. Vérifiez les permissions du répertoire <code>conf/</code>.";
            } else {
                header('Location: install.php?step=3');
                exit;
            }
        } catch (PDOException $e) {
            $errors[] = 'Connexion échouée : ' . htmlspecialchars($e->getMessage(), ENT_QUOTES, 'UTF-8');
        }
    }
}

// Step 3 POST — run schema
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === '3') {
    if (!file_exists($confFile)) { header('Location: install.php?step=2'); exit; }
    if (!file_exists($schemaFile)) { $errors[] = "Fichier schema.sql introuvable ({$schemaFile})."; }

    if (!$errors) {
        require_once $confFile;
        try {
            $h   = defined('DB_HOST') ? DB_HOST : 'localhost';
            $prt = defined('DB_PORT') ? DB_PORT : 3306;
            $u   = defined('DB_USER') ? DB_USER : '';
            $p   = defined('DB_PASS') ? DB_PASS : '';
            $d   = defined('DB_NAME') ? DB_NAME : '';
            $pdo = new PDO("mysql:host=$h;port=$prt;dbname=$d;charset=utf8mb4", $u, $p, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

            $sql = file_get_contents($schemaFile);
            // Split on ; + newline, skip comments and empty lines
            $statements = array_filter(
                array_map('trim', preg_split('/;\s*\n/', $sql)),
                fn($s) => $s !== '' && !str_starts_with($s, '--')
            );
            foreach ($statements as $stmt) {
                $pdo->exec($stmt);
            }
            header('Location: install.php?step=4');
            exit;
        } catch (PDOException $e) {
            $errors[] = 'Erreur SQL : ' . htmlspecialchars($e->getMessage(), ENT_QUOTES, 'UTF-8');
        }
    }
}

// Step 4 POST — create admin user
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === '4') {
    if (!file_exists($confFile)) { header('Location: install.php?step=2'); exit; }

    $username    = trim($_POST['username'] ?? '');
    $displayName = trim($_POST['display_name'] ?? '');
    $email       = trim($_POST['email'] ?? '');
    $password    = $_POST['password'] ?? '';
    $password2   = $_POST['password2'] ?? '';

    if (!$username)            $errors[] = 'Identifiant requis.';
    if (!preg_match('/^[a-zA-Z0-9._-]{2,50}$/', $username)) $errors[] = 'Identifiant invalide (2–50 caractères, lettres/chiffres/.-_).';
    if (strlen($password) < 8) $errors[] = 'Mot de passe trop court (min. 8 caractères).';
    if ($password !== $password2) $errors[] = 'Les mots de passe ne correspondent pas.';

    if (!$errors) {
        require_once $confFile;
        try {
            $h   = defined('DB_HOST') ? DB_HOST : 'localhost';
            $prt = defined('DB_PORT') ? DB_PORT : 3306;
            $u   = defined('DB_USER') ? DB_USER : '';
            $p   = defined('DB_PASS') ? DB_PASS : '';
            $d   = defined('DB_NAME') ? DB_NAME : '';
            $pdo = new PDO("mysql:host=$h;port=$prt;dbname=$d;charset=utf8mb4", $u, $p, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

            $hash = password_hash($password, PASSWORD_DEFAULT);
            $stmt = $pdo->prepare(
                "INSERT INTO app_users (username, display_name, email, password_hash, role, force_password_change)
                 VALUES (?, ?, ?, ?, 'admin', 0)"
            );
            $stmt->execute([$username, $displayName ?: $username, $email ?: null, $hash]);
            header('Location: install.php?step=done');
            exit;
        } catch (PDOException $e) {
            if (str_contains($e->getMessage(), 'Duplicate')) {
                $errors[] = "L'identifiant «{$username}» est déjà utilisé.";
            } else {
                $errors[] = 'Erreur : ' . htmlspecialchars($e->getMessage(), ENT_QUOTES, 'UTF-8');
            }
        }
    }
}

// ---------- Prerequisites check ----------
$prereqs = [];
$prereqs[] = ['label' => 'PHP ≥ 8.1', 'ok' => PHP_VERSION_ID >= 80100, 'detail' => 'PHP ' . PHP_VERSION];
$prereqs[] = ['label' => 'Extension PDO MySQL', 'ok' => extension_loaded('pdo_mysql'), 'detail' => extension_loaded('pdo_mysql') ? 'OK' : 'Manquante'];
$prereqs[] = ['label' => 'Extension mbstring', 'ok' => extension_loaded('mbstring'), 'detail' => extension_loaded('mbstring') ? 'OK' : 'Manquante'];
$prereqs[] = ['label' => 'Écriture dans conf/', 'ok' => is_writable(dirname($confFile)) || !file_exists(dirname($confFile)), 'detail' => is_writable(dirname($confFile)) ? 'OK' : (is_dir(dirname($confFile)) ? 'Non accessible en écriture' : 'Répertoire inexistant')];
$prereqsOk = array_reduce($prereqs, fn($carry, $p) => $carry && $p['ok'], true);

// ---------- Existing DB values for prefill ----------
$prefill = ['db_host' => 'localhost', 'db_port' => '3306', 'db_name' => '', 'db_user' => ''];
if (file_exists($confFile)) {
    require_once $confFile;
    $prefill['db_host'] = defined('DB_HOST') ? DB_HOST : $prefill['db_host'];
    $prefill['db_port'] = defined('DB_PORT') ? (string)DB_PORT : $prefill['db_port'];
    $prefill['db_name'] = defined('DB_NAME') ? DB_NAME : $prefill['db_name'];
    $prefill['db_user'] = defined('DB_USER') ? DB_USER : $prefill['db_user'];
}
foreach ($prefill as $k => $v) {
    $prefill[$k] = htmlspecialchars($v, ENT_QUOTES, 'UTF-8');
}
?>
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Installation — Casa Members</title>
<link rel="stylesheet" href="css/vendor/bootstrap.min.css">
<style>
  body { background: #f0f4f8; }
  .install-card { max-width: 560px; margin: 3rem auto; }
  .step-badge { font-size: .75rem; letter-spacing: .05em; text-transform: uppercase; }
  .prereq-row { display: flex; justify-content: space-between; align-items: center; padding: .35rem 0; border-bottom: 1px solid #e9ecef; font-size: .9rem; }
  .prereq-row:last-child { border-bottom: none; }
</style>
</head>
<body>
<div class="install-card">
  <div class="text-center mb-4">
    <h1 class="h4 fw-bold">Casa Members</h1>
    <p class="text-muted small">Assistant d'installation</p>
  </div>

  <!-- Progress -->
  <?php
  $steps = ['1' => 'Prérequis', '2' => 'Base de données', '3' => 'Schéma', '4' => 'Compte admin'];
  $currentIdx = array_search($step, array_keys($steps));
  ?>
  <?php if ($step !== 'done'): ?>
  <div class="d-flex gap-2 mb-4">
    <?php foreach ($steps as $s => $label): ?>
    <?php
      $idx = array_search($s, array_keys($steps));
      $cls = $idx < $currentIdx ? 'bg-success text-white' : ($s === $step ? 'bg-primary text-white' : 'bg-light text-muted');
    ?>
    <div class="flex-fill text-center rounded p-2 small fw-semibold <?= $cls ?>">
      <?= (string)($idx + 1) ?>. <?= $label ?>
    </div>
    <?php endforeach ?>
  </div>
  <?php endif ?>

  <?php if ($errors): ?>
  <div class="alert alert-danger">
    <ul class="mb-0 ps-3">
      <?php foreach ($errors as $e): ?>
      <li><?= $e ?></li>
      <?php endforeach ?>
    </ul>
  </div>
  <?php endif ?>

  <!-- ===== STEP 1 — Prerequisites ===== -->
  <?php if ($step === '1'): ?>
  <div class="card shadow-sm">
    <div class="card-body">
      <h2 class="h5 mb-3">Prérequis</h2>
      <div class="mb-3">
        <?php foreach ($prereqs as $pr): ?>
        <div class="prereq-row">
          <span><?= $pr['label'] ?></span>
          <span class="<?= $pr['ok'] ? 'text-success fw-semibold' : 'text-danger fw-semibold' ?>">
            <?= $pr['ok'] ? '✓' : '✗' ?> <?= htmlspecialchars($pr['detail'], ENT_QUOTES, 'UTF-8') ?>
          </span>
        </div>
        <?php endforeach ?>
      </div>
      <?php if ($prereqsOk): ?>
      <a href="install.php?step=2" class="btn btn-primary w-100">Continuer</a>
      <?php else: ?>
      <div class="alert alert-warning mb-2 small">Corrigez les prérequis manquants avant de continuer.</div>
      <button class="btn btn-secondary w-100" disabled>Continuer</button>
      <?php endif ?>
    </div>
  </div>

  <!-- ===== STEP 2 — DB Connection ===== -->
  <?php elseif ($step === '2'): ?>
  <div class="card shadow-sm">
    <div class="card-body">
      <h2 class="h5 mb-1">Connexion à la base de données</h2>
      <p class="text-muted small mb-3">Les paramètres seront enregistrés dans <code>conf/db.php</code>.</p>
      <form method="post" action="install.php?step=2">
        <div class="row g-2 mb-2">
          <div class="col-8">
            <label class="form-label small fw-semibold" for="db_host">Hôte</label>
            <input type="text" class="form-control form-control-sm" id="db_host" name="db_host"
                   value="<?= $prefill['db_host'] ?>" required>
          </div>
          <div class="col-4">
            <label class="form-label small fw-semibold" for="db_port">Port</label>
            <input type="number" class="form-control form-control-sm" id="db_port" name="db_port"
                   value="<?= $prefill['db_port'] ?>" required>
          </div>
        </div>
        <div class="mb-2">
          <label class="form-label small fw-semibold" for="db_name">Nom de la base</label>
          <input type="text" class="form-control form-control-sm" id="db_name" name="db_name"
                 value="<?= $prefill['db_name'] ?>" placeholder="members" required>
        </div>
        <div class="mb-2">
          <label class="form-label small fw-semibold" for="db_user">Utilisateur</label>
          <input type="text" class="form-control form-control-sm" id="db_user" name="db_user"
                 value="<?= $prefill['db_user'] ?>" placeholder="members" required autocomplete="username">
        </div>
        <div class="mb-3">
          <label class="form-label small fw-semibold" for="db_pass">Mot de passe</label>
          <input type="password" class="form-control form-control-sm" id="db_pass" name="db_pass"
                 autocomplete="current-password">
        </div>
        <button type="submit" class="btn btn-primary w-100">Tester et enregistrer</button>
      </form>
    </div>
  </div>

  <!-- ===== STEP 3 — Schema ===== -->
  <?php elseif ($step === '3'): ?>
  <div class="card shadow-sm">
    <div class="card-body">
      <h2 class="h5 mb-1">Initialisation du schéma</h2>
      <p class="text-muted small mb-3">
        Création des tables depuis <code>schema.sql</code>.
        Les tables existantes ne seront pas modifiées (<code>CREATE TABLE IF NOT EXISTS</code>).
      </p>
      <form method="post" action="install.php?step=3">
        <button type="submit" class="btn btn-primary w-100">Créer les tables</button>
      </form>
    </div>
  </div>

  <!-- ===== STEP 4 — Admin user ===== -->
  <?php elseif ($step === '4'): ?>
  <div class="card shadow-sm">
    <div class="card-body">
      <h2 class="h5 mb-1">Compte administrateur</h2>
      <p class="text-muted small mb-3">Ce compte sera le premier admin de l'application.</p>
      <form method="post" action="install.php?step=4">
        <div class="mb-2">
          <label class="form-label small fw-semibold" for="username">Identifiant</label>
          <input type="text" class="form-control form-control-sm" id="username" name="username"
                 value="<?= htmlspecialchars($_POST['username'] ?? '', ENT_QUOTES, 'UTF-8') ?>"
                 placeholder="admin" required autocomplete="username"
                 pattern="[a-zA-Z0-9._-]{2,50}">
          <div class="form-text">2–50 caractères, lettres/chiffres/.-_</div>
        </div>
        <div class="mb-2">
          <label class="form-label small fw-semibold" for="display_name">Nom affiché</label>
          <input type="text" class="form-control form-control-sm" id="display_name" name="display_name"
                 value="<?= htmlspecialchars($_POST['display_name'] ?? '', ENT_QUOTES, 'UTF-8') ?>"
                 placeholder="Administrateur">
        </div>
        <div class="mb-2">
          <label class="form-label small fw-semibold" for="email">E-mail <span class="text-muted fw-normal">(optionnel)</span></label>
          <input type="email" class="form-control form-control-sm" id="email" name="email"
                 value="<?= htmlspecialchars($_POST['email'] ?? '', ENT_QUOTES, 'UTF-8') ?>">
        </div>
        <div class="mb-2">
          <label class="form-label small fw-semibold" for="password">Mot de passe</label>
          <input type="password" class="form-control form-control-sm" id="password" name="password"
                 required minlength="8" autocomplete="new-password">
          <div class="form-text">Minimum 8 caractères.</div>
        </div>
        <div class="mb-3">
          <label class="form-label small fw-semibold" for="password2">Confirmer le mot de passe</label>
          <input type="password" class="form-control form-control-sm" id="password2" name="password2"
                 required autocomplete="new-password">
        </div>
        <button type="submit" class="btn btn-primary w-100">Créer le compte et terminer</button>
      </form>
    </div>
  </div>

  <!-- ===== DONE ===== -->
  <?php elseif ($step === 'done'): ?>
  <div class="card shadow-sm border-success">
    <div class="card-body text-center py-4">
      <div class="fs-1 mb-2">✓</div>
      <h2 class="h5 mb-1">Installation terminée</h2>
      <p class="text-muted small mb-3">
        La base de données est initialisée et votre compte admin est créé.<br>
        Vous pouvez supprimer <code>install.php</code> une fois connecté.
      </p>
      <a href="index.php" class="btn btn-success">Accéder à l'application</a>
    </div>
  </div>
  <?php endif ?>

  <p class="text-center text-muted mt-3" style="font-size:.75rem">
    Casa Members — <a href="https://github.com/pvollenweider/casa-membres" class="text-muted">AGPL-3.0</a>
  </p>
</div>
</body>
</html>
