; log4php.debug = true
log4php.rootLogger=OFF, A1
log4php.appender.A1=LoggerAppenderDailyFile
log4php.appender.A1.file=../logs/%s.log
log4php.appender.A1.layout=LoggerPatternLayout
log4php.appender.A1.layout.ConversionPattern=%d [%t] [%X{server.REMOTE_ADDR}/%X{server.REMOTE_USER}] %r %-5p %c %M.%L %x - %m%n
