<?php
define('APP_ENTRY', true);
/**
 * Token-based password setup for new users (public page, no login required).
 *
 * The invite token is generated by an admin when creating a new app user account.
 *
 * @copyright 2026 Philippe Vollenweider
 * @license   AGPL-3.0-or-later <https://www.gnu.org/licenses/agpl-3.0.html>
 */
require_once __DIR__ . '/includes/lib/bootstrap.php';
require_once __DIR__ . '/locales/resources_fr.php';

$token = trim($_GET['token'] ?? '');
$error = '';
$done  = false;

if ($token === '') {
    http_response_code(400);
    $error = $GLOBAL['invalidLink'];
} else {
    $stmt = $pdo->prepare(
        "SELECT id, username, display_name FROM app_users
         WHERE reset_token = ? AND token_expires_at > NOW() AND is_active = 1 LIMIT 1"
    );
    $stmt->execute([$token]);
    $user = $stmt->fetchObject();

    if (!$user) {
        $error = $GLOBAL['linkExpired'];
    } elseif ($_SERVER['REQUEST_METHOD'] === 'POST') {
        $pw1 = $_POST['pw1'] ?? '';
        $pw2 = $_POST['pw2'] ?? '';
        if (strlen($pw1) < 8) {
            $error = $GLOBAL['passwordTooShort'];
        } elseif ($pw1 !== $pw2) {
            $error = $GLOBAL['passwordsMismatch'];
        } else {
            $pdo->prepare(
                "UPDATE app_users SET password_hash=?, force_password_change=0, reset_token=NULL, token_expires_at=NULL WHERE id=?"
            )->execute([password_hash($pw1, PASSWORD_DEFAULT), $user->id]);
            $done = true;
        }
    }
}
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?= $GLOBAL['setMyPassword'] ?> — <?= htmlspecialchars($appSettings['org_name'] ?: $GLOBAL['memberManagement'], ENT_QUOTES, 'UTF-8') ?></title>
  <link rel="stylesheet" href="css/vendor/bootstrap.min.css">
  <link rel="stylesheet" href="css/custom.css">
</head>
<body class="d-flex align-items-center justify-content-center" style="min-height:100vh;background:var(--ca-ground)">
<div class="card shadow-sm border-0" style="max-width:400px;width:100%">
  <div class="card-body p-4">
    <h5 class="mb-4"><?= htmlspecialchars($appSettings['org_name'] ?: $GLOBAL['memberManagement'], ENT_QUOTES, 'UTF-8') ?> — <?= $GLOBAL['setMyPassword'] ?></h5>

    <?php if ($done): ?>
      <div class="alert alert-success">
        <i class="fas fa-check-circle me-2" aria-hidden="true"></i>
        <?= $GLOBAL['passwordSetSuccess'] ?>
      </div>

    <?php elseif ($error): ?>
      <div class="alert alert-danger"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></div>
      <?php if (!$user ?? true): ?>
        <a href="login.php" class="btn btn-outline-secondary btn-sm"><?= $GLOBAL['backToLogin'] ?></a>
      <?php endif ?>

    <?php else: ?>
      <p class="text-muted mb-3" style="font-size:0.875rem">
        <?= sprintf($GLOBAL['welcomeUser'], htmlspecialchars($user->display_name ?: $user->username, ENT_QUOTES, 'UTF-8')) ?>
        <?= $GLOBAL['choosePasswordActivate'] ?>
      </p>
      <form method="post" action="set-password.php?token=<?= urlencode($token) ?>">
        <div class="mb-3">
          <label for="pw1" class="form-label form-label-sm"><?= $GLOBAL['password'] ?></label>
          <input type="password" class="form-control form-control-sm" id="pw1" name="pw1"
                 minlength="8" required autofocus autocomplete="new-password">
          <div class="form-text"><?= $GLOBAL['minPasswordHint'] ?></div>
        </div>
        <div class="mb-4">
          <label for="pw2" class="form-label form-label-sm"><?= $GLOBAL['confirmPassword'] ?></label>
          <input type="password" class="form-control form-control-sm" id="pw2" name="pw2"
                 minlength="8" required autocomplete="new-password">
        </div>
        <button type="submit" class="btn btn-primary btn-sm w-100"><?= $GLOBAL['setPasswordBtn'] ?></button>
      </form>
    <?php endif ?>
  </div>
</div>
</body>
</html>
